version: '3'
services:
  go-server:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    ports:
      - "8081:8081"
    volumes:
      - .:/daily-words

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: daily-words
    volumes:
      - .:/var/lib/mysql